### ISSUE TITLE
font files aren't copied to the 'dist' folder

### ISSUE THREAD

**Issue by lfuelling** [micromata/generator-bootstrap-kickstart#24]
The Glyphicon fonts from Bootstrap aren't copied into the `dist` directory when I run `grunt build`.

Steps to reproduce:
1. run `yo bootstrap-kickstart` in an empty folder
2. select only to install the minimum of files
3. put some Glyphicons into the markup
4. run `grunt build`

In the `Gruntfile.js` at line 295:

```javascript
copy: {
      assets: {
        expand: true,
        src: [
          'assets/css/*.min.css',
          'assets/fonts/**/*',
          'assets/img/**/*',
          // Bower libs needed for oldIEs. The rest is concatenated via the bower_concat task.
          'libs/html5shiv/dist/html5shiv-printshiv.min.js',
          'libs/respondJs/dest/respond.min.js',
        ],
        dest: '<%= config.dist %>/'
      },
    },
```

The files in `asstes/fonts` are copied, but when I keep the folder structure of BSKS, the Bootstrap fonts don't belong there.

**Comment by mischah** [comment]
Thanks.

Fixed with d914b72a94baf172d8bc6d291b59a978714cafd3 in develop branch. Will make it in the next patch release very very soon.

**Comment by mischah** [comment]
Ist im Master und in Release v1.2.3

**Comment by lfuelling** [comment]
:+1:
