### ISSUE TITLE
Deprecation warnings when using the generator

### ISSUE THREAD

**Issue by lfuelling** [micromata/generator-bootstrap-kickstart#37]
Hi @mischah,

I'm getting some deprecation warnings when I set up a new project using the generator:

```
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
```

Thought I'd let you know :smile:

**Comment by mischah** [comment]
Thanks. These warnings been there for a while. They come from subdependencies and I can’t get rid of them from this codebase.

Just ignore them like I do :smirk: 

I think about digging into the subdependencies to create pull request for lifting the depraceted modules. But that is a whole other story. So I’ll close this issue.

LG
