### ISSUE TITLE
Update generator to use bs kickstart v3

### ISSUE THREAD

**Issue by nicolaisueper** [micromata/generator-bootstrap-kickstart#43]
Pretty self explanatory :)

I'll do this within the next week.

**Comment by mischah** [comment]
👍 

Let me know if you need help. Going to lift generator to v.1.x.x and ES6ify the codebase in the next few days.

**Comment by mischah** [comment]
> Going to lift generator to v.1.x.x and ES6ify the codebase in the next few days.

Done. See #44 

A few tests are failing locally but are green on Travis. It’s super weird.
Would love to know if tests run successfully on your machine.

**Comment by nicolaisueper** [comment]
`npm run test` ran successful.

<details>
➜  generator-bootstrap-kickstart git:(master) npm run test

> generator-bootstrap-kickstart@2.4.1 test /home/nerk/Workspace/generator-bootstrap-kickstart
> mocha



  bootstrap-kickstart with default options
    ✓ should create package manager files
    ✓ should have an empty string as banner within the Gruntfile
    ✓ should create dot files
    ✓ should have `/dist` directory in .gitignore
    ✓ should create handlebars files
    ✓ should create other project files
    ✓ should create assets
    ✓ should import all LESS files within my-theme.less file
    ✓ should render author name and email within the comments of JavaScript files
    ✓ should set the namespace within JavaScript files according to prompted project name
    ✓ should have a valid bower.json file
    ✓ should have a valid package.json file
    ✓ should have a valid .jshintrc file
    ✓ should have a valid .bowerrc file
    ✓ should have a .postinstall.js file
    ✓ should not have dependencies to support oldIEs
    ✓ should not handle oldIE related files within Grunt tasks
    ✓ should not reference oldIE related files within HTML files
    ✓ should reference module skeleton in default template
    ✓ should not include »browsehappy« message
    ✓ should not include conditional classes to address oldIEs
    ✓ should render project name and description in bower.json
    ✓ should render project name and description in package.json
    ✓ should render project name and description in README.md
    ✓ should render project name in HTML files
    ✓ should render author name within the meta tags of HTML files
    ✓ should have the default output paths within the Gruntfile
    ✓ should not have a `gitadd` task within the Gruntfile
    ✓ should not have dev dependency `grunt-git` in package.json
    ✓ should have authors name in bower.json, package.json and LICENSE
    ✓ should have authors email in bower.json and package.json
    ✓ should have authors URL in package.json and LICENSE
    ✓ should have the current year within the LICENSE
    ✓ should have a MIT LICENSE
    ✓ should have the initial version number in bower.json and package.json
    ✓ should have the homepage and repository in bower.json and package.json
    ✓ should have the issue tracker url in package.json

  bootstrap-kickstart with banner
    ✓ should have the message like defined in the template of the Gruntfile

  bootstrap-kickstart with oldIE support
    ✓ should have a valid bower.json file
    ✓ should have dependencies to support oldIEs
    ✓ should handle oldIE related files within Grunt tasks
    ✓ should reference oldIE related files within HTML files
    ✓ should include »browsehappy« message
    ✓ should include conditional classes to address oldIEs

  bootstrap-kickstart with custom output paths
    ✓ should have the prompted output paths within the Gruntfile

  bootstrap-kickstart without an open source license
    ✓ should have authors name in LICENSE
    ✓ should have authors URL in LICENSE
    ✓ should have the current year within the LICENSE
    ✓ should not have a open source license

  bootstrap-kickstart with Apache License, Version 2.0
    ✓ should have authors name in LICENSE
    ✓ should have authors URL in LICENSE
    ✓ should have the current year within the LICENSE
    ✓ should have a Apache license

  bootstrap-kickstart with GNU General Public License
    ✓ should have authors name in LICENSE
    ✓ should have authors URL in LICENSE
    ✓ should have the current year within the LICENSE
    ✓ should have a GNU General Public License

  bootstrap-kickstart with less boilerplate code
    ✓ should create just the essential handlebars files
    ✓ should not include navigation and content in index.hbs
    ✓ should not reference module skeleton in default template
    ✓ should create just a single JavaScript file (base.js)
    ✓ should create just the essential LESS files
    ✓ should only import the essential LESS files within my-theme.less file

  bootstrap-kickstart with `dist` added to version control
    ✓ should not have `/dist` directory in .gitignore
    ✓ should have dev dependency `grunt-git` in package.json
    ✓ should have a `gitadd` task within the Gruntfile

  bootstrap-kickstart using --yo-rc flag
    ✓ should create package manager files
    ✓ should create dot files
    ✓ should have `/dist` directory in .gitignore
    ✓ should create handlebars files
    ✓ should create other project files
    ✓ should create assets
    ✓ should import all LESS files within my-theme.less file
    ✓ should render author name and email within the comments of JavaScript files
    ✓ should set the namespace within JavaScript files according to prompted project name
    ✓ should have a valid bower.json file
    ✓ should have a valid package.json file
    ✓ should have a valid .jshintrc file
    ✓ should have a valid .bowerrc file
    ✓ should have a .postinstall.js file
    ✓ should not have dependencies to support oldIEs
    ✓ should not handle oldIE related files within Grunt tasks
    ✓ should not reference oldIE related files within HTML files
    ✓ should reference module skeleton in default template
    ✓ should not include »browsehappy« message
    ✓ should not include conditional classes to address oldIEs
    ✓ should render project name and description in bower.json
    ✓ should render project name and description in package.json
    ✓ should render project name and description in README.md
    ✓ should render project name in HTML files
    ✓ should render author name within the meta tags of HTML files
    ✓ should have the default output paths within the Gruntfile
    ✓ should not have a `gitadd` task within the Gruntfile
    ✓ should not have dev dependency `grunt-git` in package.json
    ✓ should have authors name in bower.json, package.json and LICENSE
    ✓ should have authors email in bower.json and package.json
    ✓ should have authors URL in package.json and LICENSE
    ✓ should have the current year within the LICENSE
    ✓ should have a MIT LICENSE
    ✓ should have the initial version number in bower.json and package.json
    ✓ should have the homepage and repository in bower.json and package.json
    ✓ should have the issue tracker url in package.json


  102 passing (3s)


> generator-bootstrap-kickstart@2.4.1 posttest /home/nerk/Workspace/generator-bootstrap-kickstart
> grunt lint

Running "eslint:target" (eslint) task

Done.


Execution Time (2017-04-10 12:08:42 UTC+2)
eslint:target  1.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 1.3s

</details>

**Comment by nicolaisueper** [comment]
@mischah is the `_moduleSkeleton.js` template still needed in v3?

**Comment by nicolaisueper** [comment]
Done. See 1d8d56d
